# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_check_update = false

  config.vm.synced_folder "../", "/uthread"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "4096"
  end

  config.vm.provision "file", source: ".tmux.conf", destination: ".tmux.conf"
  config.vm.provision "file", source: ".zshrc", destination: ".zshrc"
  config.vm.provision "shell", path: "provision.sh", privileged: false
end
